### ISSUE TITLE
[BUG] Hover effect for "My Second post"

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [Vyvy-vi/blog#2]
# Bug Report

## Describe the bug
- When we hover onto other headings like "Vyvy-vi's Blogs" and "My First post" everything seems to be perfect but hovering upon the "My Second post" shows some difference.
- All others becomes bold black after hovering but the "My Second post" becomes white which is invisible in the light mode at least. 

## Expected behavior
- All the hover styles for the blog titles should be the same to develop a sense of continuity. 

## Screenshots/ Video

https://user-images.githubusercontent.com/53310847/118592603-d382c300-b7c3-11eb-97b4-9c5f2e0a1f17.mp4

**Comment by Vyvy-vi** [comment]
:O That was fast xD
Thanks for opening an issue!!! 🎉 

The earlier implementation was buggy and not well-polished, since it relied completely on pelican.
The current version uses Jekyll with custom theme-ing

**Comment by Vyvy-vi** [comment]
I am going to close this issue, however, thanks for the opening it.
You also get the 🟩 . I'll keep this in mind while building the updated site with Jekyll

**Comment by kaiwalyakoparkar** [comment]
Yeah! sure. :)
